<div class="o-comment-ui--unavailable-message" style="clear: both; font-style: italic; font-size: {{fontSize}}{{^fontSize}}14px{{/fontSize}}; font-family: BentonSans, Arial; {{style}}">
    {{{message}}}
    {{^message}}
        It seems we're having a problem loading comments for you. Apologies. Hopefully it's temporary, but if you continue to experience this difficulty, please contact <a href="mailto:help@ft.com">help@ft.com</a>.
    {{/message}}
</div>
