<div class="o-comment-ui--overlay-explanation">
    <div class="o-comment-ui--overlay-explanation-text-container">
        <div class="o-comment-ui--overlay-explanation-text-bg">
            <div class="o-comment-ui--overlay-explanation-text">
                {{text}}
            </div>
        </div>
    </div>
    <div class="o-comment-ui--overlay-explanation-image-wrapper">
        <div class="o-comment-ui--overlay-explanation-image-container">
            <div class="o-comment-ui--overlay-explanation-image-inner-container">
                <span class="o-comment-ui--overlay-explanation-image o-comment-ui--overlay-explanation-{{type}}">&nbsp;</span>
            </div>
        </div>
    </div>
</div>
<div class="o-comment-ui--clear"></div>
